### PR TITLE
Flexspi imx9 support

### PR DESCRIPTION
**Pull request by joukkone**
Pre-review for: 

https://github.com/tiiuae/nuttx/commit/be77c57ac9853169ddb7c41f7c2c343e21ddb9e0

Other patches are already merged to apache master

### CODE REVIEW

**Review by jlaitine — APPROVED** [review]
LGTM! Do you plan to upstream this one to apache nuttx?

**Review by jlaitine — CHANGES_REQUESTED** [review]
Let's add the common parts for NOR initialization to this same PR?

**Comment by jlaitine** [comment]
I added the NOR driver part inside NuttX, added automatic detection for M25P devices. It is true that this needs to be extended if other than M25P devices are used, but I think this structure is a more solid starting point than copying NXP stuff blindly.

I modified the way how pages/sectors are treated for the MTD (page size is 256 bytes, subsector erase is 4K).
There was some really fishy cache operations, I tried to fix those as well.

Tested the stufff by opening the device, writing 3MB of data and reading it back. Seems to work

**Comment by jlaitine** [comment]
This seems to be working, pushing it to upstream review.

**Review by jlaitine — APPROVED** [review]

**Comment by jlaitine** [comment]
Upstream review requested in https://github.com/tiiuae/saluki-nxp93/pull/7 . Let's wait with this until that gets merged to avoid unnecessary merge conflicts.

**Review by jpaali — APPROVED** [review]
LGTM!

**Pull request merged**
