### PR TITLE
I2c fixes

### PR DESCRIPTION
**Pull request by jlaitine**
## Summary

This fixes some issues with initializing, re-initializing and resetting mpfs i2c + adds some debug capabilities for the future use if ever needed

## Impact

Fixes the issue where a failing magnetometer (wire getting loose) knocks out cold the whole bus, including voltage measurements, lidar lite and barometers.

## Testing

On-desk tested with saluki-v2 with core-i2c

### CODE REVIEW

**Review by eenurkka — APPROVED** [review]
Looks right!

**Review by pussuw — APPROVED** [review]

**Comment by jlaitine** [comment]
I added one more commit to this PR, to recover better from warm reboot

**Review by pussuw — APPROVED** [review]

**Comment by jlaitine** [comment]
There is still problems reported by testing. Not merging this PR yet, but will continue with measuring the buses after warm reset

**Comment by eenurkka** [comment]
Just a desperate idea, try setting SMBus_Reset to 1?

"The I2C protocol specification does not require a specific bus time-out period and typically, the slave device can hold (clock-stretch) the clock line low indefinitely. The SMBus protocol requires a bus time-out of 35 ms, and the PMBus™ protocol requires a bus time-out period of 25 to 35 ms. The purpose of implementing a bus time-out is to prevent stalled devices from indefinitely holding the bus during communication. Although not required by the normal I2C specification, a defined bus time-out may be advantageous as a fail-safe, in events where a stall in communication occurs."

CoreI2C:
```
SMBus_Reset W Writing a one to this bit will force the clock line low until 35 ms has 
been exceeded, thus resetting the entire bus as per the SMBus  Specification Version 2.0. 
Usage: When the channel is used as a host controller (master), the 
user can decide to reset the bus by holding the clock line low 
35ms. Slaves must react to this event and reset themselves.
```

**Comment by jlaitine** [comment]
Merging this->

**Pull request merged**
