### PR TITLE
Disable linker relaxed addressing when loading gp

### PR DESCRIPTION
**Pull request by jnippula**

### CODE REVIEW

**Comment by jlaitine** [comment]
Sorry guys, I updated our nuttx baseline to be on top of released 12.1.0, so now these PR's need rebase...

**Comment by jnippula** [comment]
Need to rebase this after sbi code relocation is done, as this code is also relocated into different source file.

**Review by eenurkka — APPROVED** [review]
Tried this, works after the relocation changes. I wonder what was the original reason to not have this way, maybe at mpfs_head.S (we have it there, is the other unnecessary in this patch?):
.option push
.option norelax
  la  gp, __global_pointer$
.option pop

got it wrong (in mpfs_head.S), or maybe a different toolchain was used, or something else I don't know.

**Comment by jnippula** [comment]
> Tried this, works after the relocation changes. I wonder what was the original reason to not have this way, maybe at mpfs_head.S (we have it there, is the other unnecessary in this patch?): .option push .option norelax la gp, __global_pointer$ .option pop
> 
> got it wrong (in mpfs_head.S), or maybe a different toolchain was used, or something else I don't know.

Yes, looks like the gp is already set before the mpfs_opensbi_prepare_hart() is called, so in that sense the gp loading in _prepare_hart function could be removed.

**Comment by pussuw** [comment]
> > Tried this, works after the relocation changes. I wonder what was the original reason to not have this way, maybe at mpfs_head.S (we have it there, is the other unnecessary in this patch?): .option push .option norelax la gp, __global_pointer$ .option pop
> > got it wrong (in mpfs_head.S), or maybe a different toolchain was used, or something else I don't know.
> 
> Yes, looks like the gp is already set before the mpfs_opensbi_prepare_hart() is called, so in that sense the gp loading in _prepare_hart function could be removed.

It all depends if opensbi uses gp relative instructions. I'm more concerned about mpfs_exception_opensbi.

I think our bootloader uses gp-relative instructions but it sets gp in mpfs_head.S

**Review by pussuw — APPROVED** [review]
LGTM

**Pull request merged**
