### PR TITLE
Bootloader patches

### PR DESCRIPTION
**Pull request by eenurkka**
Add 2 patches for the bootloader

### CODE REVIEW

**Review by pussuw — APPROVED** [review]

**Review by jlaitine — APPROVED** [review]

**Comment by pussuw** [comment]
Seems like NuttX size has increased so much that the "standalone" target no longer fits:
 riscv-none-elf-ld: /home/runner/work/nuttx/nuttx/sources/nuttx/nuttx section `.text' will not fit in region `envm'
riscv-none-elf-ld: region `envm' overflowed by 3312 bytes

Maybe just remove the target entirely ?

**Comment by pussuw** [comment]
The ARM build error is from upstream:
audio/wm8994.c: In function 'wm8994_audio_output':
Error: audio/wm8994.c:1898:3: error: implicit declaration of function 'up_mdelay' [-Werror=implicit-function-declaration]
 1898 |   up_mdelay(40);
      |   ^~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:109: wm8994.o] Error 1
make[1]: Target 'libdrivers.a' not remade because of errors.
make: *** [tools/LibTargets.mk:107: drivers/libdrivers.a] Error 2
make: Target 'all' not remade because of errors.

**Comment by eenurkka** [comment]
> Maybe just remove the target entirely ?
I was thinking the same

**Review by pussuw — APPROVED** [review]

**Comment by eenurkka** [comment]
Maybe this is ok to  merge?

**Comment by pussuw** [comment]
Merge away

**Pull request merged**
