### PR TITLE
mpfs_ethernet.c: increase GMAC_RX_UNITSIZE

### PR DESCRIPTION
**Pull request by jnippula**
Set RX buffer size to max frame length to be able to receive MC side MTU size frames

### CODE REVIEW

**Review by pussuw — APPROVED** [review]
LGTM, although the suggestion about having a separate kconfig variable does sound tempting as well.

**Comment by jnippula** [comment]
> LGTM, although the suggestion about having a separate kconfig variable does sound tempting as well.

Now when you say it, I'll think I'll do that instead, so it would be consistent with the TX buffer.

**Comment by jnippula** [comment]
I was thinking is there any reason to use different packet sizes for RX and TX, but just use the same size/config for both?

**Comment by pussuw** [comment]
> I was thinking is there any reason to use different packet sizes for RX and TX, but just use the same size/config for both?

To me it would make sense to just use the MTU for both, shouldn't that be enough ?

**Review by pussuw — APPROVED** [review]

**Pull request merged**
