### PR TITLE
fs_poll: race condition protection when modifying revents value (1/2)

### PR DESCRIPTION
**Pull request by t-salminen**
pollfd revents value is occasionally zeroed by race condition when poll_notify() is called. This results to false timeout return value from poll().

This behavior was found in uart loopback test when test application called tcdrain() before polling uart driver.

Upstream has a fix for the similar problem, but it is implemented only for serial-driver https://github.com/apache/nuttx/commit/bbb7f436d4faa33f283ac6f756b1bc9e88056dd7.

### CODE REVIEW

**Review by jlaitine — APPROVED** [review]
This fixes the race, yes. Can @pussuw also have a look? I think upstream fix is wrong....

**Comment by jlaitine** [comment]
> Can you explain to me what the race is / how it happens. It is not immediately obvious.

poll_notify is called from both irq context and ouside. The read-modify-write for revents should be protected here, unless it can be somehow secured that there are no concurrent calls to poll_notify.

Also I am not sure yet how the whole thing works when the poll notify is also called with events which are not subscribed in fds, but that is different thing, just looked suspicious to my eye. In the upstream commit the whole call to poll_notify is wrapped inside critical section AND sched lock inside serial driver, which is very odd....

**Comment by pussuw** [comment]
> > Can you explain to me what the race is / how it happens. It is not immediately obvious.
> 
> poll_notify is called from both irq context and ouside. 

Ok I did not realize that. Thought it always comes from the device and from ISR. This is a clear issue then.

**Review by pussuw — APPROVED** [review]

**Comment by pussuw** [comment]
>Also I am not sure yet how the whole thing works when the poll notify is also called with events which are not subscribed in fds, but that is different thing, just looked suspicious to my eye. In the upstream commit the whole call to poll_notify is wrapped inside critical section AND sched lock inside serial driver, which is very odd....

Very likely they did not find the fault here and had to lock down everything imaginable in the driver to fix it.

**Pull request merged**
